[package]

name = "algo"
version = "1.0.0-beta.2"
authors = ["Anthony Nowell <anthony@algorithmia.com>"]
build = "build.rs"

[dependencies]
docopt = "*"
rustc-serialize = "*"
chan = "*"
toml = "*"
rpassword = "*"

[dependencies.algorithmia]
version = "*"
git = "https://github.com/anowell/algorithmia_rust.git"

[build-dependencies]
chrono = "*"

