[package]

name = "algo"
version = "0.7.0"
authors = ["Anthony Nowell <anthony@algorithmia.com>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"

[dependencies.algorithmia]
version = "*"
git = "https://github.com/anowell/algorithmia_rust.git"
