[package]

name = "algo"
version = "1.0.0-beta.2"
authors = ["Anthony Nowell <anthony@algorithmia.com>"]
build = "build.rs"

[dependencies]
docopt = "0.6.80"
rustc-serialize = "0.3.19"
chan = "0.1.18"
toml = "0.1.28"
rpassword = "0.2.0"
algorithmia = { git = "http://github.com/anowell/algorithmia-rust" }

[build-dependencies]
chrono = "0.2.21"

