[package]

name = "algorithmia-cli"
version = "0.4.0"
authors = ["Anthony Nowell <anthony@algorithmia.com>"]

[dependencies]
getopts = "*"

[dependencies.algorithmia]
version = "*"
git = "https://github.com/anowell/algorithmia_rust.git"
