name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
          ALGORITHMIA_API_KEY: ${{ secrets.algo_key }}
      run: cargo test --verbose
